name: EntityActor
main: SharpyKurth\Loader
version: 1.1.0
author: KurthMC
api: [2.0.0, 3.3.1, 3.3.4, 4.0.0]
permissions:
  actor.command:
    default: op
    children:
      actor.command.create:
        default: op
      actor.command.update:
        default: op
      actor.command.remove:
        default: op
